# Generated by Django 3.2.19 on 2023-07-14 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_accessrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webpage',
            name='id',
        ),
        migrations.AlterField(
            model_name='webpage',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
