# Generated by Django 3.2.19 on 2023-07-14 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20230714_1347'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccessRecord',
            new_name='Record',
        ),
    ]
